#!/usr/bin/env node
/**
 * build.js — Netlify build entry point.
 *
 * Suburb pages are only rebuilt when REBUILD_SUBURBS=true env var is set.
 * Otherwise, cached suburb pages from previous builds are restored.
 * This lets you deploy CSS/JS/config changes without regenerating 14,512 suburb pages.
 *
 * To trigger a suburb rebuild:
 *   - Set REBUILD_SUBURBS=true in Netlify env vars, then deploy
 *   - Or use the Admin → Suburbs tab "Rebuild Pages" button (triggers deploy hook)
 *   - The env var is automatically cleared after the build
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = __dirname;
const SUBURB_DIR = path.join(ROOT, 'suburb');
const INVEST_DIR = path.join(ROOT, 'invest');
// Netlify provides a persistent cache directory between builds
const CACHE_DIR = process.env.NETLIFY_CACHE_DIR || path.join(ROOT, '.cache');
const CACHE_SUBURB = path.join(CACHE_DIR, 'suburb');
const CACHE_INVEST = path.join(CACHE_DIR, 'invest');
const CACHE_STAMP = path.join(CACHE_DIR, 'suburb-build-stamp.json');
// Index report (AdSense gate summary) — regenerated by build-suburbs.js,
// cached here so it survives non-rebuild deploys and can be fetched by admin.
const REPORT_FILE = 'data/suburb-index-report.json';
const CACHE_REPORT = path.join(CACHE_DIR, 'suburb-index-report.json');

// Netlify sets INCOMING_HOOK_TITLE when a build hook triggers the deploy
// Admin "Rebuild Suburbs" button names the hook "Suburb rebuild (admin)"
const hookTitle = process.env.INCOMING_HOOK_TITLE || '';
const FORCE_SENTINEL = path.join(ROOT, '.force-rebuild');
const sentinelPresent = fs.existsSync(FORCE_SENTINEL);
const explicitRebuild = process.env.REBUILD_SUBURBS === 'true'
  || hookTitle.toLowerCase().includes('suburb')
  || sentinelPresent;

if (sentinelPresent) {
  // Sentinel-triggered rebuild: log loudly so it's obvious in Netlify
  // deploy output. Delete the sentinel immediately so the NEXT deploy
  // doesn't keep rebuilding — this is a one-shot mechanism. The file
  // is committed empty to the repo whenever we need a guaranteed
  // refresh; the build erases it so we never accidentally rebuild
  // the 14,512-page set on every subsequent commit.
  console.log('═══════════════════════════════════════════════════════════════════');
  console.log('  [build]  .force-rebuild sentinel detected — full suburb rebuild');
  console.log('═══════════════════════════════════════════════════════════════════');
  try { fs.unlinkSync(FORCE_SENTINEL); console.log('[build] Sentinel deleted — next deploy will use cache as normal.'); }
  catch (e) { console.warn('[build] Could not delete sentinel:', e.message); }
}

// Files whose changes invalidate the suburb-page cache. When any of these is
// newer than the cache stamp, we force a rebuild on the next deploy so a
// template tweak or build-script edit doesn't sit dormant behind the cache
// for weeks until someone manually pokes REBUILD_SUBURBS=true.
const SUBURB_CACHE_DEPS = [
  'build/build-suburbs.js',
  'build/apply-abs-data.js',
  'templates/suburb-page.html',
  'templates/state-hub.html',
  'templates/city-page.html',
  'data/suburbs.json',
];

function getSitemapFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.match(/^sitemap-suburbs-.*\.xml$/));
}

function cacheExists() {
  return fs.existsSync(CACHE_SUBURB) && fs.existsSync(CACHE_INVEST) && getSitemapFiles(CACHE_DIR).length > 0;
}

// Returns true when any tracked dependency has been modified since the cache
// was last written. Falls back to "stale" (force rebuild) when the stamp is
// missing or unreadable — safer than serving outdated HTML to users + Google.
function cacheIsStale() {
  if (!fs.existsSync(CACHE_STAMP)) return true;
  let stampTime;
  try {
    const stamp = JSON.parse(fs.readFileSync(CACHE_STAMP, 'utf8'));
    stampTime = stamp.date ? new Date(stamp.date).getTime() : 0;
  } catch (e) {
    return true;
  }
  if (!stampTime) return true;
  for (const rel of SUBURB_CACHE_DEPS) {
    const abs = path.join(ROOT, rel);
    if (!fs.existsSync(abs)) continue;
    const mtime = fs.statSync(abs).mtimeMs;
    if (mtime > stampTime) {
      console.log('[build] Cache stale: ' + rel + ' modified after last build');
      return true;
    }
  }
  return false;
}

const shouldRebuild = explicitRebuild || cacheIsStale();

function copyDir(src, dest) {
  execSync(`cp -a "${src}" "${dest}"`, { stdio: 'inherit' });
}

function restoreFromCache() {
  console.log('[build] Restoring suburb pages from cache...');
  if (fs.existsSync(CACHE_SUBURB)) copyDir(CACHE_SUBURB, SUBURB_DIR);
  if (fs.existsSync(CACHE_INVEST)) copyDir(CACHE_INVEST, INVEST_DIR);
  for (const f of getSitemapFiles(CACHE_DIR)) {
    fs.copyFileSync(path.join(CACHE_DIR, f), path.join(ROOT, f));
  }
  if (fs.existsSync(CACHE_REPORT)) {
    fs.copyFileSync(CACHE_REPORT, path.join(ROOT, REPORT_FILE));
  }
  if (fs.existsSync(CACHE_STAMP)) {
    const stamp = JSON.parse(fs.readFileSync(CACHE_STAMP, 'utf8'));
    console.log(`[build] Restored ${stamp.count} suburb pages (built ${stamp.date})`);
  }
}

function saveToCache() {
  console.log('[build] Saving suburb pages to cache...');
  fs.mkdirSync(CACHE_DIR, { recursive: true });
  // Clean old cache
  if (fs.existsSync(CACHE_SUBURB)) execSync(`rm -rf "${CACHE_SUBURB}"`, { stdio: 'inherit' });
  if (fs.existsSync(CACHE_INVEST)) execSync(`rm -rf "${CACHE_INVEST}"`, { stdio: 'inherit' });
  copyDir(SUBURB_DIR, CACHE_SUBURB);
  copyDir(INVEST_DIR, CACHE_INVEST);
  // Cache all split sitemap files
  for (const f of getSitemapFiles(ROOT)) {
    fs.copyFileSync(path.join(ROOT, f), path.join(CACHE_DIR, f));
  }
  // Cache index report so it survives non-rebuild deploys
  const reportPath = path.join(ROOT, REPORT_FILE);
  if (fs.existsSync(reportPath)) {
    fs.copyFileSync(reportPath, CACHE_REPORT);
  }
  // Save timestamp
  const data = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'suburbs.json'), 'utf8'));
  fs.writeFileSync(CACHE_STAMP, JSON.stringify({
    date: new Date().toISOString(),
    count: data.length
  }));
}

async function buildSuburbs() {
  console.log('[build] Rebuilding suburb pages...');

  // Step 1: Fetch enhanced ABS data (income, centroids, rent, mortgage, dwelling types).
  // This runs against the ABS ArcGIS FeatureServer and takes ~60s for all 14,500 suburbs.
  // Skipped if SKIP_ABS_FETCH=true (useful for local dev without internet).
  let absFetchOk = false;
  if (process.env.SKIP_ABS_FETCH !== 'true') {
    console.log('[build] Fetching enhanced ABS data (income, centroids, rent, mortgage)...');
    try {
      // Run as a child process to keep each script's module scope clean
      execSync('node build/fetch-abs-enhanced.js', { stdio: 'inherit', cwd: __dirname });
      console.log('[build] ABS fetch complete. Applying real data to suburbs.json...');
      execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
      absFetchOk = true;
    } catch (e) {
      // Loud banner — silent ABS-fetch failures were the root cause of all
      // suburbs.json enrichment fields (median_rent_weekly, distance_to_cbd,
      // lat/lng, house_percentage) staying null and degrading the suburb-page
      // SERP snippet. Always log this loudly so it's visible in Netlify logs.
      console.error('');
      console.error('═══════════════════════════════════════════════════════════════════');
      console.error('  [build]  ABS ENHANCED FETCH FAILED — using stale suburbs.json');
      console.error('═══════════════════════════════════════════════════════════════════');
      console.error('  Error: ' + e.message);
      console.error('  Effect: suburb pages will keep null rent / distance / lat/lng');
      console.error('          fields. Phase-3 SEO meta upgrade depends on these.');
      console.error('  Likely causes:');
      console.error('   - ABS ArcGIS endpoint changed schema or URL (most likely)');
      console.error('   - Netlify build sandbox blocked outbound to services1.arcgis.com');
      console.error('   - Rate limit / transient outage (retry the deploy)');
      console.error('  Verify locally: node build/fetch-abs-enhanced.js');
      console.error('═══════════════════════════════════════════════════════════════════');
      console.error('');
      // Still run apply-abs-data.js to at least get the logic fixes applied
      try {
        execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
      } catch (e2) {
        console.error('[build] apply-abs-data.js also failed:', e2.message);
      }
    }
  } else {
    console.log('[build] SKIP_ABS_FETCH=true — skipping ABS fetch, using existing data.');
    execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
  }

  // Step 2: Build all suburb HTML pages from updated suburbs.json
  require('./build/build-suburbs.js');
  saveToCache();

  // Step 3: Data-health audit — count how many suburbs have the enrichment
  // fields populated. Surfaces silently-broken pipelines on every rebuild
  // so the next deploy makes any regression obvious in Netlify logs.
  try {
    const subs = JSON.parse(fs.readFileSync(path.join(__dirname, 'data', 'suburbs.json'), 'utf8'));
    const total = subs.length;
    const c = {
      rent:     subs.filter(s => s.median_rent_weekly).length,
      mortgage: subs.filter(s => s.median_mortgage_monthly).length,
      distance: subs.filter(s => s.distance_to_cbd != null).length,
      housePct: subs.filter(s => s.house_percentage != null).length,
      latLng:   subs.filter(s => s.lat != null).length,
    };
    const pct = (n) => total ? Math.round(n / total * 100) + '%' : '0%';
    console.log('[build] DATA HEALTH (suburbs.json enrichment field coverage):');
    console.log('         median_rent_weekly      ' + c.rent     + '/' + total + ' (' + pct(c.rent)     + ')');
    console.log('         median_mortgage_monthly ' + c.mortgage + '/' + total + ' (' + pct(c.mortgage) + ')');
    console.log('         distance_to_cbd         ' + c.distance + '/' + total + ' (' + pct(c.distance) + ')');
    console.log('         house_percentage        ' + c.housePct + '/' + total + ' (' + pct(c.housePct) + ')');
    console.log('         lat / lng               ' + c.latLng   + '/' + total + ' (' + pct(c.latLng)   + ')');
    if (absFetchOk && c.rent === 0) {
      console.error('[build] WARNING: ABS fetch reported success but enrichment fields');
      console.error('        are 100% null. apply-abs-data.js may be failing silently.');
    }
    if (c.rent === 0) {
      console.warn('[build] Phase-3 SEO meta-description will fall back to income-only');
      console.warn('        variant. Populate the ABS enhanced data to light up the');
      console.warn('        richer "median rent $X/wk, income $Yk, pop Z" SERP snippet.');
    }
  } catch (e) {
    console.warn('[build] Data-health audit skipped:', e.message);
  }
}

async function buildBlog() {
  // Always rebuild the blog on every deploy — the content set is small
  // (20-30 posts) and it's stored in Redis, so we want the latest published
  // posts to show up without requiring a cache-bust.
  if (process.env.SKIP_BLOG_BUILD === 'true') {
    console.log('[build] SKIP_BLOG_BUILD=true — skipping blog build');
    return;
  }
  try {
    const blog = require('./build/build-blog.js');
    await blog.main();
  } catch (e) {
    // Non-fatal: blog failures shouldn't block the rest of the deploy.
    console.warn('[build] Blog build failed (non-fatal):', e.message);
  }
}

// ── Main ──

(async () => {
  if (shouldRebuild) {
    if (explicitRebuild) {
      console.log('[build] Explicit rebuild trigger — regenerating all suburb pages');
    } else {
      console.log('[build] Cache stale (template / build script changed) — regenerating');
    }
    await buildSuburbs();
  } else if (cacheExists()) {
    restoreFromCache();
  } else {
    console.log('[build] No cache found — building suburb pages for the first time');
    await buildSuburbs();
  }
  await buildBlog();
  // Pre-render the 6 legal-stack pages so the .md content ships baked-in.
  // Eliminates CLS 0.640 caused by legal.js client-side injection. Cheap
  // (~50 ms), runs every deploy.
  try {
    execSync('node build/build-legal.js', { stdio: 'inherit' });
  } catch (e) {
    console.warn('[build] build-legal failed (non-blocking):', e.message);
  }
  // Soft validation — never blocks the deploy. Catches sitemap-core staleness.
  try {
    execSync('node build/audit-sitemap.js', { stdio: 'inherit' });
  } catch (e) {
    console.warn('[build] Sitemap audit reported issues (non-blocking):', e.message);
  }
  console.log('[build] Done.');
})();
