#!/usr/bin/env node
/**
 * build.js — Netlify build entry point.
 *
 * Suburb pages auto-rebuild ONLY when the *content* of a suburb dependency
 * (templates, build-suburbs.js, apply-abs-data.js, data/suburbs.json) changes —
 * detected via a content hash stored in the cache stamp. Otherwise the cached
 * pages from the previous build are restored, so CSS/JS/config-only deploys are
 * instant and don't regenerate the 14,512-page set.
 *
 * Why content hash, not mtime: git does not preserve file mtimes across Netlify's
 * fresh checkouts, so an mtime comparison saw every file as "modified" and rebuilt
 * every deploy (which is why a committed .force-rebuild sentinel used to mask it).
 *
 * To force a rebuild manually:
 *   - Set REBUILD_SUBURBS=true in Netlify env vars, then deploy, or
 *   - Use the Admin → Suburbs "Rebuild Pages" button (POSTs a build hook whose
 *     INCOMING_HOOK_TITLE contains "suburb"), or
 *   - Commit an empty .force-rebuild file (one-shot; the build deletes it).
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

const ROOT = __dirname;
const SUBURB_DIR = path.join(ROOT, 'suburb');
const INVEST_DIR = path.join(ROOT, 'invest');
// Netlify provides a persistent cache directory between builds
const CACHE_DIR = process.env.NETLIFY_CACHE_DIR || path.join(ROOT, '.cache');
const CACHE_SUBURB = path.join(CACHE_DIR, 'suburb');
const CACHE_INVEST = path.join(CACHE_DIR, 'invest');
const CACHE_STAMP = path.join(CACHE_DIR, 'suburb-build-stamp.json');
// Index report (AdSense gate summary) — regenerated by build-suburbs.js,
// cached here so it survives non-rebuild deploys and can be fetched by admin.
const REPORT_FILE = 'data/suburb-index-report.json';
const CACHE_REPORT = path.join(CACHE_DIR, 'suburb-index-report.json');

// Netlify sets INCOMING_HOOK_TITLE when a build hook triggers the deploy
// Admin "Rebuild Suburbs" button names the hook "Suburb rebuild (admin)"
const hookTitle = process.env.INCOMING_HOOK_TITLE || '';
const FORCE_SENTINEL = path.join(ROOT, '.force-rebuild');
const sentinelPresent = fs.existsSync(FORCE_SENTINEL);
const explicitRebuild = process.env.REBUILD_SUBURBS === 'true'
  || hookTitle.toLowerCase().includes('suburb')
  || sentinelPresent;

if (sentinelPresent) {
  // Sentinel-triggered rebuild: log loudly so it's obvious in Netlify
  // deploy output. Delete the sentinel immediately so the NEXT deploy
  // doesn't keep rebuilding — this is a one-shot mechanism. The file
  // is committed empty to the repo whenever we need a guaranteed
  // refresh; the build erases it so we never accidentally rebuild
  // the 14,512-page set on every subsequent commit.
  console.log('═══════════════════════════════════════════════════════════════════');
  console.log('  [build]  .force-rebuild sentinel detected — full suburb rebuild');
  console.log('═══════════════════════════════════════════════════════════════════');
  try { fs.unlinkSync(FORCE_SENTINEL); console.log('[build] Sentinel deleted — next deploy will use cache as normal.'); }
  catch (e) { console.warn('[build] Could not delete sentinel:', e.message); }
}

// Files whose CONTENT invalidates the suburb-page cache. When the hash of any of
// these differs from the hash stored in the last build's cache stamp, we rebuild
// on the next deploy so a template tweak or build-script edit goes live without a
// manual poke. Content hash (not mtime) because git doesn't preserve mtimes across
// Netlify checkouts.
const SUBURB_CACHE_DEPS = [
  'build/build-suburbs.js',
  'build/apply-abs-data.js',
  'build/merge-market-current.js',
  'templates/suburb-page.html',
  'templates/state-hub.html',
  'data/suburbs.json',
  'data/market-current.json',
];

// Hash the dependency file contents (path + bytes, in fixed order). Missing files
// hash to a stable marker so add/remove is detected too.
function computeDepsHash() {
  const h = crypto.createHash('sha256');
  for (const rel of SUBURB_CACHE_DEPS) {
    h.update(rel + '\n');
    const abs = path.join(ROOT, rel);
    if (fs.existsSync(abs)) h.update(fs.readFileSync(abs));
    else h.update('<missing>');
    h.update('\0');
  }
  return h.digest('hex');
}

// IMPORTANT: compute this ONCE, now, at the as-checked-out state — BEFORE the build
// mutates data/suburbs.json (apply-abs-data.js enriches it in place). Both the
// staleness check and the stamp we write must use this checkout-time hash, or the
// post-enrichment hash would never match the next checkout and we'd rebuild forever.
const DEPS_HASH = computeDepsHash();

function getSitemapFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.match(/^sitemap-suburbs-.*\.xml$/));
}

function cacheExists() {
  return fs.existsSync(CACHE_SUBURB) && fs.existsSync(CACHE_INVEST) && getSitemapFiles(CACHE_DIR).length > 0;
}

// Stale when the cache stamp is missing/unreadable, predates content-hashing
// (no depsHash field — forces one transitional rebuild after this change ships),
// or when the current dependency hash differs from the cached one. Falling back to
// "stale" on any doubt is safer than serving outdated HTML to users + Google.
function cacheIsStale() {
  if (!fs.existsSync(CACHE_STAMP)) return true;
  let stamp;
  try {
    stamp = JSON.parse(fs.readFileSync(CACHE_STAMP, 'utf8'));
  } catch (e) {
    return true;
  }
  if (!stamp || !stamp.depsHash) return true; // pre-hash cache → rebuild once
  if (stamp.depsHash !== DEPS_HASH) {
    console.log('[build] Cache stale: suburb template/data/build-script content changed');
    return true;
  }
  return false;
}

const shouldRebuild = explicitRebuild || cacheIsStale();

function copyDir(src, dest) {
  execSync(`cp -a "${src}" "${dest}"`, { stdio: 'inherit' });
}

function restoreFromCache() {
  console.log('[build] Restoring suburb pages from cache...');
  if (fs.existsSync(CACHE_SUBURB)) copyDir(CACHE_SUBURB, SUBURB_DIR);
  if (fs.existsSync(CACHE_INVEST)) copyDir(CACHE_INVEST, INVEST_DIR);
  for (const f of getSitemapFiles(CACHE_DIR)) {
    fs.copyFileSync(path.join(CACHE_DIR, f), path.join(ROOT, f));
  }
  // Restore the sitemap INDEX too — the committed sitemap.xml can lag the split
  // files (it once shipped with only core+blog, dropping every suburb URL from
  // Google's view), so the rebuild-generated index must survive non-rebuild deploys.
  const cachedIndex = path.join(CACHE_DIR, 'sitemap.xml');
  if (fs.existsSync(cachedIndex)) fs.copyFileSync(cachedIndex, path.join(ROOT, 'sitemap.xml'));
  if (fs.existsSync(CACHE_REPORT)) {
    fs.copyFileSync(CACHE_REPORT, path.join(ROOT, REPORT_FILE));
  }
  if (fs.existsSync(CACHE_STAMP)) {
    const stamp = JSON.parse(fs.readFileSync(CACHE_STAMP, 'utf8'));
    console.log(`[build] Restored ${stamp.count} suburb pages (built ${stamp.date})`);
  }
}

function saveToCache() {
  console.log('[build] Saving suburb pages to cache...');
  fs.mkdirSync(CACHE_DIR, { recursive: true });
  // Clean old cache
  if (fs.existsSync(CACHE_SUBURB)) execSync(`rm -rf "${CACHE_SUBURB}"`, { stdio: 'inherit' });
  if (fs.existsSync(CACHE_INVEST)) execSync(`rm -rf "${CACHE_INVEST}"`, { stdio: 'inherit' });
  copyDir(SUBURB_DIR, CACHE_SUBURB);
  copyDir(INVEST_DIR, CACHE_INVEST);
  // Cache all split sitemap files + the index that references them
  for (const f of getSitemapFiles(ROOT)) {
    fs.copyFileSync(path.join(ROOT, f), path.join(CACHE_DIR, f));
  }
  const indexPath = path.join(ROOT, 'sitemap.xml');
  if (fs.existsSync(indexPath)) fs.copyFileSync(indexPath, path.join(CACHE_DIR, 'sitemap.xml'));
  // Cache index report so it survives non-rebuild deploys
  const reportPath = path.join(ROOT, REPORT_FILE);
  if (fs.existsSync(reportPath)) {
    fs.copyFileSync(reportPath, CACHE_REPORT);
  }
  // Save timestamp
  const data = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'suburbs.json'), 'utf8'));
  fs.writeFileSync(CACHE_STAMP, JSON.stringify({
    date: new Date().toISOString(),
    count: data.length,
    depsHash: DEPS_HASH // checkout-time hash, so the next build can compare apples-to-apples
  }));
}

async function buildSuburbs() {
  console.log('[build] Rebuilding suburb pages...');

  // Step 1: Fetch enhanced ABS data (income, centroids, rent, mortgage, dwelling types).
  // This runs against the ABS ArcGIS FeatureServer and takes ~60s for all 14,500 suburbs.
  // Skipped if SKIP_ABS_FETCH=true (useful for local dev without internet).
  let absFetchOk = false;
  if (process.env.SKIP_ABS_FETCH !== 'true') {
    console.log('[build] Fetching enhanced ABS data (income, centroids, rent, mortgage)...');
    try {
      // Run as a child process to keep each script's module scope clean
      execSync('node build/fetch-abs-enhanced.js', { stdio: 'inherit', cwd: __dirname });
      console.log('[build] ABS fetch complete. Applying real data to suburbs.json...');
      execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
      absFetchOk = true;
    } catch (e) {
      // Loud banner — silent ABS-fetch failures were the root cause of all
      // suburbs.json enrichment fields (median_rent_weekly, distance_to_cbd,
      // lat/lng, house_percentage) staying null and degrading the suburb-page
      // SERP snippet. Always log this loudly so it's visible in Netlify logs.
      console.error('');
      console.error('═══════════════════════════════════════════════════════════════════');
      console.error('  [build]  ABS ENHANCED FETCH FAILED — using stale suburbs.json');
      console.error('═══════════════════════════════════════════════════════════════════');
      console.error('  Error: ' + e.message);
      console.error('  Effect: suburb pages will keep null rent / distance / lat/lng');
      console.error('          fields. Phase-3 SEO meta upgrade depends on these.');
      console.error('  Likely causes:');
      console.error('   - ABS ArcGIS endpoint changed schema or URL (most likely)');
      console.error('   - Netlify build sandbox blocked outbound to services1.arcgis.com');
      console.error('   - Rate limit / transient outage (retry the deploy)');
      console.error('  Verify locally: node build/fetch-abs-enhanced.js');
      console.error('═══════════════════════════════════════════════════════════════════');
      console.error('');
      // Still run apply-abs-data.js to at least get the logic fixes applied
      try {
        execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
      } catch (e2) {
        console.error('[build] apply-abs-data.js also failed:', e2.message);
      }
    }
  } else {
    console.log('[build] SKIP_ABS_FETCH=true — skipping ABS fetch, using existing data.');
    execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
  }

  // Step 1c: fold CURRENT market data (median rent / sale price from free
  // CC BY 4.0 state-gov open data, pre-extracted + verified into
  // data/market-current.json) into suburbs.json. Rebuild-only; keeps the 2021
  // Census fields as a dated baseline.
  try {
    execSync('node build/merge-market-current.js', { stdio: 'inherit', cwd: __dirname });
  } catch (e) {
    console.error('[build] merge-market-current failed (keeping existing current_* fields):', e.message);
  }

  // Step 2: Build all suburb HTML pages from updated suburbs.json
  require('./build/build-suburbs.js');
  saveToCache();

  // Step 3: Data-health audit — count how many suburbs have the enrichment
  // fields populated. Surfaces silently-broken pipelines on every rebuild
  // so the next deploy makes any regression obvious in Netlify logs.
  try {
    const subs = JSON.parse(fs.readFileSync(path.join(__dirname, 'data', 'suburbs.json'), 'utf8'));
    const total = subs.length;
    const c = {
      rent:     subs.filter(s => s.median_rent_weekly).length,
      mortgage: subs.filter(s => s.median_mortgage_monthly).length,
      distance: subs.filter(s => s.distance_to_cbd != null).length,
      housePct: subs.filter(s => s.house_percentage != null).length,
      latLng:   subs.filter(s => s.lat != null).length,
    };
    const pct = (n) => total ? Math.round(n / total * 100) + '%' : '0%';
    console.log('[build] DATA HEALTH (suburbs.json enrichment field coverage):');
    console.log('         median_rent_weekly      ' + c.rent     + '/' + total + ' (' + pct(c.rent)     + ')');
    console.log('         median_mortgage_monthly ' + c.mortgage + '/' + total + ' (' + pct(c.mortgage) + ')');
    console.log('         distance_to_cbd         ' + c.distance + '/' + total + ' (' + pct(c.distance) + ')');
    console.log('         house_percentage        ' + c.housePct + '/' + total + ' (' + pct(c.housePct) + ')');
    console.log('         lat / lng               ' + c.latLng   + '/' + total + ' (' + pct(c.latLng)   + ')');
    if (absFetchOk && c.rent === 0) {
      console.error('[build] WARNING: ABS fetch reported success but enrichment fields');
      console.error('        are 100% null. apply-abs-data.js may be failing silently.');
    }
    if (c.rent === 0) {
      console.warn('[build] Phase-3 SEO meta-description will fall back to income-only');
      console.warn('        variant. Populate the ABS enhanced data to light up the');
      console.warn('        richer "median rent $X/wk, income $Yk, pop Z" SERP snippet.');
    }
  } catch (e) {
    console.warn('[build] Data-health audit skipped:', e.message);
  }
}

async function buildBlog() {
  // Blog is dark by default (strategy change, Aug 2026: the site is one
  // product — the /journey planner). The CMS infrastructure stays dormant;
  // set BLOG_ENABLE=true in Netlify env vars to bring the blog back.
  if (process.env.BLOG_ENABLE !== 'true') {
    console.log('[build] blog disabled (BLOG_ENABLE not set)');
    return;
  }
  try {
    const blog = require('./build/build-blog.js');
    await blog.main();
  } catch (e) {
    // Non-fatal: blog failures shouldn't block the rest of the deploy.
    console.warn('[build] Blog build failed (non-fatal):', e.message);
  }
}

// ── Main ──

(async () => {
  if (shouldRebuild) {
    if (explicitRebuild) {
      console.log('[build] Explicit rebuild trigger — regenerating all suburb pages');
    } else {
      console.log('[build] Cache stale (template / build script changed) — regenerating');
    }
    await buildSuburbs();
  } else if (cacheExists()) {
    restoreFromCache();
  } else {
    console.log('[build] No cache found — building suburb pages for the first time');
    await buildSuburbs();
  }
  await buildBlog();
  // Pre-render the 6 legal-stack pages so the .md content ships baked-in.
  // Eliminates CLS 0.640 caused by legal.js client-side injection. Cheap
  // (~50 ms), runs every deploy.
  try {
    execSync('node build/build-legal.js', { stdio: 'inherit' });
  } catch (e) {
    console.warn('[build] build-legal failed (non-blocking):', e.message);
  }
  // Soft validation — never blocks the deploy. Catches sitemap-core staleness.
  try {
    execSync('node build/audit-sitemap.js', { stdio: 'inherit' });
  } catch (e) {
    console.warn('[build] Sitemap audit reported issues (non-blocking):', e.message);
  }
  console.log('[build] Done.');
})();
