#!/usr/bin/env node
/**
 * build.js — Netlify build entry point.
 *
 * Suburb pages are only rebuilt when REBUILD_SUBURBS=true env var is set.
 * Otherwise, cached suburb pages from previous builds are restored.
 * This lets you deploy CSS/JS/config changes without regenerating 14,512 suburb pages.
 *
 * To trigger a suburb rebuild:
 *   - Set REBUILD_SUBURBS=true in Netlify env vars, then deploy
 *   - Or use the Admin → Suburbs tab "Rebuild Pages" button (triggers deploy hook)
 *   - The env var is automatically cleared after the build
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = __dirname;
const SUBURB_DIR = path.join(ROOT, 'suburb');
const INVEST_DIR = path.join(ROOT, 'invest');
// Netlify provides a persistent cache directory between builds
const CACHE_DIR = process.env.NETLIFY_CACHE_DIR || path.join(ROOT, '.cache');
const CACHE_SUBURB = path.join(CACHE_DIR, 'suburb');
const CACHE_INVEST = path.join(CACHE_DIR, 'invest');
const CACHE_STAMP = path.join(CACHE_DIR, 'suburb-build-stamp.json');
// Index report (AdSense gate summary) — regenerated by build-suburbs.js,
// cached here so it survives non-rebuild deploys and can be fetched by admin.
const REPORT_FILE = 'data/suburb-index-report.json';
const CACHE_REPORT = path.join(CACHE_DIR, 'suburb-index-report.json');

// Netlify sets INCOMING_HOOK_TITLE when a build hook triggers the deploy
// Admin "Rebuild Suburbs" button names the hook "Suburb rebuild (admin)"
const hookTitle = process.env.INCOMING_HOOK_TITLE || '';
const shouldRebuild = process.env.REBUILD_SUBURBS === 'true' || hookTitle.toLowerCase().includes('suburb');

function getSitemapFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.match(/^sitemap-suburbs-.*\.xml$/));
}

function cacheExists() {
  return fs.existsSync(CACHE_SUBURB) && fs.existsSync(CACHE_INVEST) && getSitemapFiles(CACHE_DIR).length > 0;
}

function copyDir(src, dest) {
  execSync(`cp -a "${src}" "${dest}"`, { stdio: 'inherit' });
}

function restoreFromCache() {
  console.log('[build] Restoring suburb pages from cache...');
  if (fs.existsSync(CACHE_SUBURB)) copyDir(CACHE_SUBURB, SUBURB_DIR);
  if (fs.existsSync(CACHE_INVEST)) copyDir(CACHE_INVEST, INVEST_DIR);
  for (const f of getSitemapFiles(CACHE_DIR)) {
    fs.copyFileSync(path.join(CACHE_DIR, f), path.join(ROOT, f));
  }
  if (fs.existsSync(CACHE_REPORT)) {
    fs.copyFileSync(CACHE_REPORT, path.join(ROOT, REPORT_FILE));
  }
  if (fs.existsSync(CACHE_STAMP)) {
    const stamp = JSON.parse(fs.readFileSync(CACHE_STAMP, 'utf8'));
    console.log(`[build] Restored ${stamp.count} suburb pages (built ${stamp.date})`);
  }
}

function saveToCache() {
  console.log('[build] Saving suburb pages to cache...');
  fs.mkdirSync(CACHE_DIR, { recursive: true });
  // Clean old cache
  if (fs.existsSync(CACHE_SUBURB)) execSync(`rm -rf "${CACHE_SUBURB}"`, { stdio: 'inherit' });
  if (fs.existsSync(CACHE_INVEST)) execSync(`rm -rf "${CACHE_INVEST}"`, { stdio: 'inherit' });
  copyDir(SUBURB_DIR, CACHE_SUBURB);
  copyDir(INVEST_DIR, CACHE_INVEST);
  // Cache all split sitemap files
  for (const f of getSitemapFiles(ROOT)) {
    fs.copyFileSync(path.join(ROOT, f), path.join(CACHE_DIR, f));
  }
  // Cache index report so it survives non-rebuild deploys
  const reportPath = path.join(ROOT, REPORT_FILE);
  if (fs.existsSync(reportPath)) {
    fs.copyFileSync(reportPath, CACHE_REPORT);
  }
  // Save timestamp
  const data = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'suburbs.json'), 'utf8'));
  fs.writeFileSync(CACHE_STAMP, JSON.stringify({
    date: new Date().toISOString(),
    count: data.length
  }));
}

async function buildSuburbs() {
  console.log('[build] Rebuilding suburb pages...');

  // Step 1: Fetch enhanced ABS data (income, centroids, rent, mortgage, dwelling types).
  // This runs against the ABS ArcGIS FeatureServer and takes ~60s for all 14,500 suburbs.
  // Skipped if SKIP_ABS_FETCH=true (useful for local dev without internet).
  if (process.env.SKIP_ABS_FETCH !== 'true') {
    console.log('[build] Fetching enhanced ABS data (income, centroids, rent, mortgage)...');
    try {
      // Run as a child process to keep each script's module scope clean
      execSync('node build/fetch-abs-enhanced.js', { stdio: 'inherit', cwd: __dirname });
      console.log('[build] ABS fetch complete. Applying real data to suburbs.json...');
      execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
    } catch (e) {
      // Non-fatal: if ABS fetch fails (e.g. network issue), continue with existing data
      console.warn('[build] Warning: ABS enhanced fetch failed — building with existing data.');
      console.warn(e.message);
      // Still run apply-abs-data.js to at least get the logic fixes applied
      try {
        execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
      } catch (e2) {
        console.warn('[build] Warning: apply-abs-data.js also failed:', e2.message);
      }
    }
  } else {
    console.log('[build] SKIP_ABS_FETCH=true — skipping ABS fetch, using existing data.');
    execSync('node build/apply-abs-data.js', { stdio: 'inherit', cwd: __dirname });
  }

  // Step 2: Build all suburb HTML pages from updated suburbs.json
  require('./build/build-suburbs.js');
  saveToCache();
}

// ── Main ──

(async () => {
  if (shouldRebuild) {
    console.log('[build] REBUILD_SUBURBS=true — regenerating all suburb pages');
    await buildSuburbs();
  } else if (cacheExists()) {
    restoreFromCache();
  } else {
    console.log('[build] No cache found — building suburb pages for the first time');
    await buildSuburbs();
  }
  console.log('[build] Done.');
})();
